version: "3.8"
services:
  cloudflaretunnel:
    container_name: cloudflaretunnel-ToDoListBE
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      to-do-list-network:
        ipv4_address: 172.28.127.4
  todoapp:
    container_name: todo_app
    build: ./ToDoListFE
    image: jmtodolist:v1
    ports:
      - "80:80"
    expose:
      - 80
    networks:
      to-do-list-network:
        ipv4_address: 172.28.127.3
    volumes:
      - app-data:/var/www/html
  todoserver:
    build: ./ToDoListBE
    container_name: todo_server
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USER: ${SPRING_DATASOURCE_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8081:8080"
    networks:
      to-do-list-network:
        ipv4_address: 172.28.127.2
    volumes:
      - server-data:/var/
  db:
    image: postgres
    container_name: todo_db
    restart: always
    volumes:
      - ./ToDoListBE/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - pg-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      to-do-list-network:
        ipv4_address: 172.28.127.1

volumes:
  pg-data:
  server-data:
  app-data:
networks:
  to-do-list-network:
    ipam:
      config:
        - subnet: 172.28.0.0/16
